# Generated by Django 4.2.13 on 2025-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
