"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "insecure-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
# Treat common truthy values as True ("1", "true", "yes", "on")
DEBUG = os.environ.get("DEBUG", "true").strip().lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS: list[str] = []

# Allow Render-provided hostname and additional comma-separated hosts via env
render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

env_allowed_hosts = os.environ.get("ALLOWED_HOSTS")
if env_allowed_hosts:
    ALLOWED_HOSTS.extend([
        host.strip() for host in env_allowed_hosts.split(",") if host.strip()
    ])

# In dev/docker, allow common hosts if none provided
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "accounts",
    "submit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# Prefer DATABASE_URL (e.g., Render Managed Postgres). Fallback to SQLite.
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    try:
        import dj_database_url  # type: ignore
        DATABASES["default"] = dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=os.environ.get("DB_SSL_REQUIRE", "true").lower() == "true",
        )
    except Exception:
        # If parsing fails for any reason, keep SQLite fallback
        pass
else:
    # Optional: override SQLite location via env if a persistent disk is mounted
    _sqlite_path = os.environ.get("SQLITE_PATH")
    if _sqlite_path:
        DATABASES["default"]["NAME"] = _sqlite_path


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Ensure Django knows it's behind a proxy (Render)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend', # Keep the default backend as a fallback
]

# Allow frontend to connect (read from env, comma-separated)
_env_cors = os.environ.get("CORS_ALLOWED_ORIGINS")
if _env_cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _env_cors.split(",") if o.strip()]
else:
    # Defaults: local dev + production Vercel frontend
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://the-oj-project.vercel.app",
    ]

# Optional: allow origin regexes via env for preview URLs (e.g., Vercel)
_env_cors_regexes = os.environ.get("CORS_ALLOWED_ORIGIN_REGEXES")
if _env_cors_regexes:
    CORS_ALLOWED_ORIGIN_REGEXES = [r.strip() for r in _env_cors_regexes.split(",") if r.strip()]
else:
    # Allow all Vercel preview deployments
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^https:\/\/.*\\.vercel\\.app$"]

# CSRF trusted origins for admin and session-based endpoints
_env_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _env_csrf.split(",") if o.strip()]
if not CSRF_TRUSTED_ORIGINS:
    # Include the production frontend domain for cookie-based endpoints/admin if used
    CSRF_TRUSTED_ORIGINS = [
        "https://the-oj-project.vercel.app",
    ]
if render_hostname:
    # Must include scheme
    CSRF_TRUSTED_ORIGINS.append(f"https://{render_hostname}")

CORS_ALLOW_CREDENTIALS = True

# Harden cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
}
